
# Makefile

main: main.o getAddress.o evaluate.o 
	g++ -o main main.o getAddress.o HexaConversion.o DecimalConversion.o opcodeSize.o evaluate.o

main.o: main.cpp headerFiles/master.hpp
	g++ -c main.cpp

getAddress.o: getAddress.cpp
	g++ -c getAddress.cpp

HexaConversion.o:HexaConversion.hpp
	g++ -c HexaConversion.cpp

DecimalConversion.o:DecimalConversion.hpp
	g++ -c DecimalConversion.cpp

opcodeSize.o:opcodeSize.hpp
	g++ -c opcodeSize.cpp

evaluate.o:headerFiles/function.hpp  headerFiles/arithmatic.hpp headerFiles/master.hpp headerFiles/logical.hpp loadAndStore.cpp logical.cpp arithmatic.cpp
	g++ -c evaluate.cpp arithmatic.cpp logical.cpp loadAndStore.cpp



# arithmatic.o: arithmatic.cpp
# 	g++ -c arithmatic.cpp

# logical.o: logical.cpp
# 	g++ -c logical.cpp

# loadAndStore.o :loadAndStore.cpp
# 	g++ -c loadAndStore.cpp
